defaults:
  - _base

data:
  name: cifar100

model:
  task: "m_X_comp"
  num_classes: 100
  ckpt_path_A: /workspace/Illusion_Res/tmp/models/m_A_resnet50_indl32/m_B_epoch=46-val_acc=0.76.ckpt
  ckpt_path_B: none

trainer:
  max_epochs: 10
