defaults:
  - _base

data:
  name: imagenet1k

model:
  task: "m_X_comp"
  num_classes: 1000
  ckpt_path_A: /home/gus.xia/haobo/ai701-illusion-inspired-design/tmp/models/m_A_resnet50_indl224/m_A_epoch=00-val_top1_acc=0.934.ckpt
  ckpt_path_B: none

trainer:
  max_epochs: 5
  patience: 1